version: '3'
services:
  gateway:
    image: "xinin/gateway:latest"
    ports:
       - "9000:9000"
  hello:
    image: "xinin/hello:latest"
    ports:
      - "9001:9000"
  bye:
    image: "xinin/bye:latest"
    ports:
      - "9002:9000"