version: '3.2'
services:
  gateway:
    build: "./gateway"
    volumes:
      - type: bind
        source: ./gateway
        target: /app
    ports:
      - "9000:9000"
    networks:
      fargate-api:
        ipv4_address: 172.16.1.10
  hello:
    build: "./hello"
    volumes:
      - type: bind
        source: ./hello
        target: /app
    networks:
      fargate-api:
        ipv4_address: 172.16.1.12
  bye:
    build: "./bye"
    volumes:
      - type: bind
        source: ./bye
        target: /app
    networks:
      fargate-api:
        ipv4_address: 172.16.1.13
networks:
  fargate-api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
